import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container_principal}>
      <Head>
        <title>React.js | Atividade 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <header className={styles.nav}>
          <h1>React JS</h1>
        </header>

        <main className={styles.main}>
          <section className={styles.titulo}>
            <h1 className={styles.texto_h1}>React JS</h1>
            <p className={styles.texto_p}>Biblioteca Javascript para criar SPAs</p>
            <a href="#" className={styles.botao}>Site Oficial</a>
          </section>

          <section className={styles.requisitos}>
            <h2 className={styles.texto_h2}>Requisitos</h2>
            <p>Veja abaixo os requisitos mínimos para aprender React.JS</p>

            <div className={styles.main_cards}>

              {/* card 1 */}
              <div className={styles.card}>
                <h1 className={styles.card_titulo}>HTML</h1>
                <p className={styles.card_texto}>Aprender a estruturar os elementos da página com HTML</p>
              </div>

              {/* card 2 */}
              <div className={styles.card}>
                <h1 className={styles.card_titulo}>CSS</h1>
                <p className={styles.card_texto}>Aprender a estilizar os elementos da página com CSS</p>
              </div>

              {/* card 3 */}
              <div className={styles.card}>
                <h1 className={styles.card_titulo}>JavaScript</h1>
                <p className={styles.card_texto}>Aprender a linguagem utilizada pelo React.js, o JavaScript</p>
              </div>

            </div>
          </section>
        </main>

        <footer className={styles.footer}>
          <p>Curso de introdução ao React.JS</p>
        </footer>
      </div>
  );
}
